- 0  # Invisibles
- 7  # Barelang FC
- 4  # Berlin United
- 29  # CAU Mountain&Sea
- 10  # Colmillos ITAM
- 20  # GeoHBots
- 6  # Hamburg Bit-Bots
- 22  # HUST-HRT
- 23  # I-Kid
- 26  # ICHIRO ITS
- 27  # Invic
- 34  # ITAndroids
- 35  # KHUBER
- 36  # Mountain
- 1  # NUbots
- 21  # RO:BIT
- 49  # SABANA HERONS
- 30  # THMOS
- 17  # ZJU Dancer
- 70  # B-Team
