- 0  # Invisibles
- 5  # B-Human
- 52  # Badger Bots
- 4  # Berlin United
- 29  # CAU Mountain&Sea
- 14  # HTWK Robots
- 24  # HULKs
- 39  # I-Teen
- 40  # Inha-United
- 27  # Invic
- 1  # NUbots
- 51  # RedbackBots
- 41  # RFC-Tsudanuma
- 11  # Rhoban
- 42  # RoboEireann
- 12  # Ruhrbot Devils
- 18  # rUNSWift
- 30  # THMOS
- 8  # whIRLwind Amsterdam
- 70  # B-Team
