- name: Invisibles
  number: 0
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
- name: NUbots
  number: 1
  fieldPlayerColors: [blue, white]
  goalkeeperColors: [blue, white]
- name: Bold Hearts
  number: 2
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
- name: Bembelbots
  number: 3
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
- name: Berlin United
  number: 4
  fieldPlayerColors: [blue, purple, white]
  goalkeeperColors: [blue, purple, white]
- name: B-Human
  number: 5
  fieldPlayerColors: [red, white]
  goalkeeperColors: [blue, purple, white, red]
- name: Hamburg Bit-Bots
  number: 6
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
- name: Barelang FC
  number: 7
  fieldPlayerColors: [blue, red]
  goalkeeperColors: [yellow, purple]
- name: whIRLwind Amsterdam
  number: 8
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
- name: WF Wolves
  number: 9
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
- name: Colmillos ITAM
  number: 10
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
- name: Rhoban
  number: 11
  fieldPlayerColors: [yellow, green]
  goalkeeperColors: [yellow, green]
- name: Ruhrbot Devils
  number: 12
  fieldPlayerColors: [yellow, black, white]
  goalkeeperColors: [yellow, black, white]
- name: Blenders FC
  number: 13
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
- name: HTWK Robots
  number: 14
  fieldPlayerColors: [blue, red]
  goalkeeperColors: [yellow, blue, red]
- name: EWS Bascorro
  number: 15
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
- name: Pumas
  number: 16
  fieldPlayerColors: [blue, red]
  goalkeeperColors: [blue, red]
- name: ZJUDancer
  number: 17
  fieldPlayerColors: [blue, purple]
  goalkeeperColors: [blue, purple]
- name: rUNSWift
  number: 18
  fieldPlayerColors: [black, yellow]
  goalkeeperColors: [black, yellow]
- name: SPQR Team
  number: 19
  fieldPlayerColors: [red, black, blue]
  goalkeeperColors: [red, black, blue]
- name: GeoHBots
  number: 20
  fieldPlayerColors: [white, blue]
  goalkeeperColors: [white, blue]
- name: RO:BIT
  number: 21
  fieldPlayerColors: [blue, red, orange, yellow]
  goalkeeperColors: [blue, red, orange, yellow]
- name: HUST-HRT
  number: 22
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
- name: I-Kid
  number: 23
  fieldPlayerColors: [blue, red]
  goalkeeperColors: [orange, yellow, blue, red]
- name: HULKs
  number: 24
  fieldPlayerColors: [blue, red, green]
  goalkeeperColors: [blue, red, green]
- name: HERoEHS
  number: 25
  fieldPlayerColors: [blue, red]
  goalkeeperColors: [yellow, blue, red]
- name: ICHIRO ITS
  number: 26
  fieldPlayerColors: [blue, red]
  goalkeeperColors: [blue, red]
- name: Invic
  number: 27
  fieldPlayerColors: [blue, white, yellow, orange, black]
  goalkeeperColors: [blue, white, yellow, orange, black]
- name: Team Sweaty
  number: 28
  fieldPlayerColors: [blue, red]
  goalkeeperColors: [blue, red]
- name: CAU Mountain&Sea
  number: 29
  fieldPlayerColors: [blue, red]
  goalkeeperColors: [blue, red]
- name: THMOS
  number: 30
  fieldPlayerColors: [red, blue]
  goalkeeperColors: [red, blue]
- name: Tsinghua Hephaestus
  number: 31
  fieldPlayerColors: [purple, red]
  goalkeeperColors: [purple, red]
- name: UT AustinVilla
  number: 32
  fieldPlayerColors: [orange, blue]
  goalkeeperColors: [orange, blue]
- name: NomadZ
  number: 33
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
- name: ITAndroids
  number: 34
  fieldPlayerColors: [red, blue]
  goalkeeperColors: [red, blue]
- name: KHUBER
  number: 35
  fieldPlayerColors: [blue, red]
  goalkeeperColors: [blue, red]
- name: Mountain
  number: 36
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
- name: Team noon
  number: 37
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
- name: WolverBot Kickers
  number: 38
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
- name: I-Teen
  number: 39
  fieldPlayerColors: [blue, red]
  goalkeeperColors: [orange, yellow, blue, red]
- name: Inha-United
  number: 40
  fieldPlayerColors: [red, blue]
  goalkeeperColors: [yellow, red, blue]
- name: RFC-Tsudanuma
  number: 41
  fieldPlayerColors: [blue, red, yellow]
  goalkeeperColors: [blue, red, yellow]
- name: RoboEireann
  number: 42
  fieldPlayerColors: [green, white, red]
  goalkeeperColors: [green, white, red]
- name: Bahia Robotics Team
  number: 43
  fieldPlayerColors: [blue, red]
  goalkeeperColors: [white, blue, red]
- name: Beihang RoboCup Team
  number: 44
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
- name: Naova
  number: 45
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
- name: BigHeroX
  number: 46
  fieldPlayerColors: [red, green]
  goalkeeperColors: [red, green]
- name: DUT Future
  number: 47
  fieldPlayerColors: [blue, red, orange, yellow]
  goalkeeperColors: [blue, red, orange, yellow]
- name: Future Becoming
  number: 48
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
- name: SABANA HERONS
  number: 49
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
- name: R-ZWEI KICKERS
  number: 50
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
- name: RedbackBots
  number: 51
  fieldPlayerColors: [red, yellow, black, white]
  goalkeeperColors: [red, yellow, black, white]
- name: Badger Bots
  number: 52
  fieldPlayerColors: [red, black, white]
  goalkeeperColors: [red, black, white]
- name: KURA
  number: 53
  fieldPlayerColors: [blue, white, red, black]
  goalkeeperColors: [blue, white, red, black]
- name: PCMS-HRG
  number: 54
  fieldPlayerColors: [blue, red]
  goalkeeperColors: [orange, yellow, blue, red]
- name: Robo-Erectus
  number: 55
  fieldPlayerColors: [blue, red, white, purple]
  goalkeeperColors: [blue, red, white, purple]
- name: RobôCIn
  number: 56
  fieldPlayerColors: [blue, white, yellow]
  goalkeeperColors: [blue, white, yellow]
- name: Robotedge
  number: 57
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
- name: SJTU Cyber Shanhai
  number: 58
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
- name: Talos Humanoid Robots
  number: 59
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
- name: Tech United
  number: 60
  fieldPlayerColors: [orange, blue]
  goalkeeperColors: [orange, blue]
- name: WarthogRobotics
  number: 61
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
- name: Water
  number: 62
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
- name: WHU United
  number: 63
  fieldPlayerColors: [blue, white]
  goalkeeperColors: [yellow, orange, blue, white]
- name: ZETIN
  number: 64
  fieldPlayerColors: [blue, white]
  goalkeeperColors: [yellow, blue, white]
- name: B-Team
  number: 70
  fieldPlayerColors: [red, blue, yellow, black, white, green, orange, purple, brown, gray]
  goalkeeperColors: [blue, yellow, black, white, green, orange, purple, brown, gray, red]
